global:
  edition: ce
  ingress:
    configureCertmanager: false
    tls:
      enabled: false  # disable TLS for local dev
  appConfig:
    waitForPostgres: true  # ensure webservice/sidekiq wait for Postgres

nginx-ingress:
  enabled: false  # disable NGINX ingress, use Traefik or port-forward instead

gitlab:
  webservice:
    ingress:
      enabled: false
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 1Gi

postgresql:
  install: true
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 1Gi

redis:
  install: true
  master:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 512Mi

gitaly:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 1Gi

webservice:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 1Gi

sidekiq:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

gitlab-runner:
  install: false  # optional, avoid running it in tiny local cluster


# https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml?utm_source=chatgpt.com
## The global properties are used to configure multiple charts at once.
## https://docs.gitlab.com/charts/charts/globals
# global:

  ## https://docs.gitlab.com/charts/charts/globals#configure-host-settings
  # hosts:
  #   domain: example.com
  #   hostSuffix:
  #   https: true
  #   externalIP:
  #   ssh:
  #   gitlab: {}
  #   minio: {}
  #   registry: {}
  #   tls: {}
  #   smartcard: {}
  #   kas: {}
  #   pages: {}
  #   openbao: {}

 ## https://docs.gitlab.com/charts/charts/globals#configure-ingress-settings
  # ingress:
  #   apiVersion: ""
  #   configureCertmanager: true
  #   useNewIngressForCerts: false
  #   provider: nginx
  #   # class:
  #   annotations: {}
  #   enabled: true
  #   tls: {}
  #   #   enabled: true
  #   #   secretName:
  #   path: /
  #   pathType: Prefix

## https://docs.gitlab.com/charts/charts/nginx/
## https://docs.gitlab.com/charts/architecture/decisions#nginx-ingress
## Installation & configuration of charts/ingress-nginx:
# nginx-ingress: &nginx-ingress
#   enabled: true
#   tcpExternalConfig: "true"
#   controller: &nginx-ingress-controller
#     podSecurityContext:
#       seccompProfile:
#         type: "RuntimeDefault"
#     image:
#       registry: registry.gitlab.com
#       image: gitlab-org/cloud-native/mirror/images/ingress-nginx/controller
#       tag: "v1.11.7"
#       digest: "sha256:016a25cf89bf7f930869ccd7cb3dd4acbe106cd4da1419804951ef9c8636f053"
#     addHeaders:
#       Referrer-Policy: strict-origin-when-cross-origin
#     config: &nginx-ingress-controller-config
#       annotation-value-word-blocklist: "load_module,lua_package,_by_lua,location,root,proxy_pass,serviceaccount,{,},',\""
#       hsts: "true"
#       hsts-include-subdomains: "false"
#       hsts-max-age: "63072000"
#       server-name-hash-bucket-size: "256"
#       use-http2: "true"
#       ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
#       ssl-protocols: "TLSv1.3 TLSv1.2"
#       server-tokens: "false"
#       # Configure smaller defaults for upstream-keepalive-*, see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration
#       upstream-keepalive-connections: 100 # Limit of 100 held-open connections
#       upstream-keepalive-time:        30s # 30 second limit for connection reuse
#       upstream-keepalive-timeout:       5 # 5 second timeout to hold open idle connections
#       upstream-keepalive-requests:   1000 # 1000 requests per connection, before recycling
#     electionID: ingress-controller-leader
#     service:
#       externalTrafficPolicy: "Local"
#       # Configure no IP families to delegate assignment to controller based on cluster config.
#       ipFamilies: []
#       ipFamilyPolicy: "PreferDualStack"
#       appProtocol: false
#       internal:
#         appProtocol: false
#     ingressClassByName: false
#     ingressClassResource:
#       name: '{{ include "ingress.class.name" $ | quote }}'
#     resources:
#       requests:
#         cpu: 100m
#         memory: 100Mi
#     publishService:
#       enabled: true
#     replicaCount: 2
#     minAvailable: 1
#     scope:
#       enabled: true
#     metrics:
#       enabled: true
#       service:
#         annotations:
#           gitlab.com/prometheus_scrape: "true"
#           gitlab.com/prometheus_port: "10254"
#           prometheus.io/scrape: "true"
#           prometheus.io/port: "10254"
#     admissionWebhooks:
#       enabled: false
#   defaultBackend:
#     podSecurityContext:
#       seccompProfile:
#         type: "RuntimeDefault"
#     resources:
#       requests:
#         cpu: 5m
#         memory: 5Mi

