# Charts config: https://docs.gitlab.com/charts/charts/
# Global config: https://docs.gitlab.com/charts/charts/globals/  
# Minimal config
global:
  edition: ce
  hosts:
    domain: localhost
    https: false
  ingress:
    class: traefik 

  kas:
    # GitLab Kubernetes Agent Server (KAS) - GitOps, Kubernetes, ...
    # https://docs.gitlab.com/charts/charts/gitlab/kas/
    enabled: false
  # minio:
    # Storage objects
    # enabled: false
  registry:
    # Docker images register
    enabled: false

certmanager-issuer:
  email: admin@localhost.com

nginx-ingress:
  enabled: false

gitlab:
  gitlab-shell:
    # Git SSH access to Gitlab
    # https://docs.gitlab.com/charts/charts/gitlab/gitlab-shell/
    service:
      type: NodePort
      NodePort: 32222

  gitaly:
    # handles Git repository storage & access
    replicas: 1

  webservice:
    # https://docs.gitlab.com/charts/charts/gitlab/webservice/
    # 1000m = 1 Full Core (200m ~ 20 % of a core)
    replicas: 1
    resources:
      # https://docs.gitlab.com/charts/charts/gitlab/webservice/#resources
      requests:
        memory: 1.25G
        cpu: 300m
      limits:
        memory: 2.5G
        cpu: 600m

  sidekiq:
    # background jobs, e.g., sending emails, cleaning data
    # https://docs.gitlab.com/charts/charts/gitlab/sidekiq/
    replicas: 1
    resources:
      # https://docs.gitlab.com/charts/charts/gitlab/sidekiq/#resources
      requests:
        memory: 2G
        cpu: 900m
      limits:
        memory: 4G
        cpu: 2

  postgresql:
    install: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  redis:
    install: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"

  kas:
    install: false
  # minio:
    # install: false
  registry:
    install: false
  gitlab-runner:
    install: false

