Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"

  config.vm.define "rcutteS" do |control|
    control.vm.hostname = "rcutteS"
    control.vm.network "private_network", ip: "192.168.56.110", virtualbox__intnet: true
    
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "rcutteS"]
      v.memory = 2048
      v.cpus = 1
    end
    control.vm.provision "shell", inline: <<-SHELL
      echo 'Hello from Server'
    SHELL
    # Initial provisioning: install K3S
    control.vm.provision "shell", path: "./setup_server.sh"

    control.vm.provision "shell", path: "./install_docker.sh"

    # Second provisioning: deploy projects
    control.vm.provision "shell", path: "./projects/deploy_projects.sh"
  end
  
  config.vm.provider "virtualbox"
end
