# Deployment docs:
# - https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        # https://github.com/hashicorp/http-echo
        image: hashicorp/http-echo
        args:
          - |
            -text=<!DOCTYPE html>
            <html>
              <head>
                <title>App3</title>
              </head>
              <body>
                <h1>Hello from App3!</h1>
              </body>
            </html>
        ports:
          - containerPort: 5678
            name: app3-d-port

