# kubernetes service docs:
# - https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
# - https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  selector:
    app: app3
  type: ClusterIP
  ports:
  - name: app3-s-port
    protocol: TCP
    port: 80
    targetPort: app3-d-port

