# Vagrant file to setup 2 VMs (1 Server: S, 1 Worker: SW)
# VM specs: 1 CPU, 512MB RAM

Vagrant.configure("2") do |config|
  # Vagrant box: https://developer.hashicorp.com/vagrant/docs/boxes#official-boxes
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202508.03.0"
  config.trigger.before :destroy do |trigger|
  trigger.run = {inline: "rm -rf /home/rmohamma/sgoinfre/goinfre/perso/rmohamma/Git/p1/confs"}
  end

  config.vm.define "rcutteS" do |control|
    control.vm.hostname = "rcutteS"
    # 192.168.0.0 – 192.168.255.255
    control.vm.network "private_network", ip: "192.168.56.110"
    
    control.vm.provider "virtualbox" do |v|
      # Configure VirtualBox: https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
      ## vagrant vbox config: https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration#vboxmanage-customizations
      ## vbox customize list: https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
      v.customize ["modifyvm", :id, "--name", "rcutteS"]
      v.memory = 512
      v.cpus = 1
    end
    # control.vm.provision "shell", inline: <<-SHELL
    #   echo 'Hello from Server'
    # SHELL
    control.vm.provision "shell", path: "scripts/install_server.sh"
  end

  config.vm.define "rcutteSW" do |control|
    control.vm.hostname = "rcutteSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "rcutteSW"]
      v.memory = 512
      v.cpus = 1
    end
    # control.vm.provision "shell", inline: <<-SHELL
    #   echo 'Hello from Worker'
    # SHELL
    control.vm.provision "shell", path: "scripts/install_worker.sh"
  end

  # Providers: https://developer.hashicorp.com/vagrant/docs/providers/basic_usage
  config.vm.provider "virtualbox"

end
