# 1. Use Python 3.11 as base image and debian
FROM python:3.11-slim

# 2. Set working directory inside container
WORKDIR /app

# 4. Copy the app code
COPY app.py .

# 5. Command to run the app
CMD ["python", "app.py"]
