# Deployment docs:
# - https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        # https://github.com/hashicorp/http-echo
        image: hashicorp/http-echo
        args:
          - "-text=Hello from App2 !"
        ports:
        - containerPort: 5678
          name: app2-d-port

