# Deployment docs:
# - https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        # https://github.com/hashicorp/http-echo
        image: hashicorp/http-echo
        args:
          - |
            -text=<!DOCTYPE html>
            <html>
              <head>
                <title>App1</title>
              </head>
              <body>
                <h1>Hello from App1!</h1>
              </body>
            </html>
        ports:
        - containerPort: 5678
          name: app1-d-port

