# kubernetes service docs:
# - https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
# - https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  type: ClusterIP
  ports:
  - name: app1-s-port
    protocol: TCP
    port: 80
    targetPort: app1-d-port

